### ISSUE TITLE
DevSecOps Road Trip - Sam Hepburn - 13th September 2021

### ISSUE THREAD

**Issue by nickebbitt** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#15]
[The idea] Due to the pandemic restrictions none of us have been able to travel and visit most European cities, never mind our favourite conferences and communities. The idea is to have a week-long 'Road Trip' where we will virtually visit a different country each day, hear from the local communities, learn from the awesome local speakers about secure development and collect souvenirs along the way. 

[The ask] I'm on the hunt for a few great communities to partner up with. We would cover all the logistics of getting the event together but would ask you to share it with your community (we could even be your September event), suggest a few awesome speakers to get involved and if you're avalible and keen to join us live on the day we'd love that.

I've added a few more details below but I'm keen to hear what you think?
Fancy getting involved? If you are, let's jump on a quick call so I can chat more about the details. 

Looking forward to hearing back form you
Sam 

[The Details] 
Dates: 13-17th September
Timing: 12:30-1:30pm CEST 

Locations: 
Mon | UK
Tues | France
Wed | Netherlands
Thur | Germany
Fri | The Nordics

**Comment by CraigMcDonaldCodes** [comment]
Event finished.
