### ISSUE TITLE
Web site content ideas/suggestions

### ISSUE THREAD

**Issue by jonbullock** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#2]
A place to discuss any ideas or suggestions the community has for the Manchester Java Community site.

**Comment by nickebbitt** [comment]
It would be interesting to hear @CraigMcDonaldCodes's thoughts/ideas so far.

**Comment by CraigMcDonaldCodes** [comment]
I have some ideas that we can start with.

**/**

- Small banner
- Info on the next get together with a link to the Meetup event
- Info on the next talk at LJC?
- Plug for the sponsor (if any)
- List some Java/JVM/ news (e.g. Foojay), not a full page, maybe just 5 or so?

**/contact**

- Meetup page
- Email
- Twitter
- Slack

**/about**

- Blurb about what the MJC is, why it exists
- List founders

**/submit-a-talk**

- Form or link to a form to request to talk at MJC or an idea for one.

**/members**

- List of members who would like a mention
- Small blurb?
- Links to any open source projects they work on

**/speakers**

- Who has spoken at the MJC
- Small blurb about them?
- Link to their contact details

**/talks**

- List all talks at the MJC
- Some way of searching
- Link to recording, if available

**/wall-of-fame**

- Top 10 speakers based on number of talks given.
- Talks that really stood out?

**/friends**

- List of other organizations, companies etc that would be okay with being associated with the MJC.

**Comment by nickebbitt** [comment]
Internally at AutoTrader we use https://www.mkdocs.org/ which has a search plugin that seems to work pretty well.

I know @CraigMcDonaldCodes was wondering whether we could have search with a static site but at least with mkdocs you can, not sure about others?

@jonbullock is a search a thing that can be done with JBake? or maybe if not, a feature request we could look to progress?

**Comment by jonbullock** [comment]
It's been done with Lunr before. But I see Algolia getting a lot of usage recently.

**Comment by CraigMcDonaldCodes** [comment]
From the initial pages I listed, I only think two need a searching/filtering/sorting dynamic element to it (talks and speakers). Not sure if we need a site wide search.

**Comment by CraigMcDonaldCodes** [comment]
Do we think we need more pages?
Do we have enough of an idea what we want to create to start making some decisions?

First one to get out the way is what we should using for the static site generation. Stay with Jekyll, go with JBake or something else?

**Comment by nickebbitt** [comment]
I think it would be cool to use JBake, and with @jonbullock on board it makes sense as we've got 1st line support direct from the creator :) 

Yeah we'll need more pages, probably start off by adding the About page where we can give some history, highlight key community members etc.

Once we have that in plave we can pretty quickly evolve the site to support the other pages we want.

**Comment by jonbullock** [comment]
Sounds good to me.

What about the design of the site? Do we want to use an 'off the shelf' design/template (i.e. https://html5up.net/) or create something from scratch using some UI/CSS framework (Bootstrap etc.)?

**Comment by nickebbitt** [comment]
I'm easy, if there are some templates that's have a good look & feel for us then that might make sense

**Comment by jonbullock** [comment]
I need to convert a template over to use one of the template engines supported in JBake so why don't I pick one that would suit MJC. If its liked we can use it, if not we can look at others. 

I'm away next week but I'll look at doing this when I'm back and report back here when I have something to show.

**Comment by nickebbitt** [comment]
sounds good, thanks @jonbullock 👍

**Comment by jonbullock** [comment]
I haven't forgotten about this, just taken me longer than I'd hoped but I've got something to show finally. I'll upload it over the weekend and provide a link here with some comments/ideas.

**Comment by nickebbitt** [comment]
great stuff, thanks

**Comment by jonbullock** [comment]
Here is the JBake template: https://jonbullock.github.io/jbake-strongly-typed/ (source files are here: https://github.com/jonbullock/jbake-strongly-typed).

I went for a template where content or body of text is primary focus in the design.

On index page I thought the 3 images would be links to last 3 Youtube videos/sessions. Not too sure about the banner area yet.

When it comes to main content area the sidebar is optional, although I've used that to display "post" metadata such as tags and recent posts, and it can go left or right of main body of text based on a simple flag in the content file being rendered.

As I said before I needed to do this for JBake so feel free to share any dislike of the template :)

**Comment by nickebbitt** [comment]
I think it looks good although the colour scheme doesn't feel very us, not sure how easy that is adjust?

Also, how do you build that? Interested in the jbake process but maybe that's one for when we apply to the MJC site

**Comment by jonbullock** [comment]
If it's just the colour scheme it should be fairly easy to change. Do you have an idea of what colours you would prefer? Or something I can pick colours from like a logo as inspiration? 

For the sake of speed I configured GitHub Pages to serve out the [docs](https://github.com/jonbullock/jbake-strongly-typed/tree/main/docs) and ran JBake locally so it produced it's output into the /docs folder and then pushed the whole repo. Not what I'd propose as a solution long term, but got the job done.

For jbake.org we use GitLab Pages for hosting and the GitLab CI system plus JBake Docker image for the build even though the main source repo is stored on GitHub.

**Comment by nickebbitt** [comment]
yeah, erm..I'm colour blind so maybe not the best person to advise on the scheme :) 

we've got the Java/Duke bee logo that we need to incorporate and I used a yellow'y theme when I created the existing site

https://manchesterjavacommunity.org/jmanc/

That may look terrible so open to other ideas and better creative input than I can provide :)

**Comment by CraigMcDonaldCodes** [comment]
Can you have a quick look at http://demo.manchesterjavacommunity.org before I stick in a PR. Still quite a bit to do but it enough for the upcoming JBake session. I'll probably put in more changes before but this gives others a chance to contribute.

@jonbullock
@nickebbitt

**Comment by nickebbitt** [comment]
Looks like a good start 👍

I have an idea that tie into the website which I'd like to discuss at some point, in fact I'll maybe just raise an issue for it.

**Comment by jonbullock** [comment]
Yeah looks good to me too. Viewing on a mobile at present and site adapts very nicely.

**Comment by jonbullock** [comment]
Going to close this and create issues for each piece of content/page so they can be worked on individually. As agreed in the last call about the web site.
