### ISSUE TITLE
Java 17 - José Paumard - 18th November 2021 @ 12:30

### ISSUE THREAD

**Issue by jonbullock** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#22]
Talk on Java 17

@jonbullock to look for speakers who are giving talks like this at the moment

**Comment by CraigMcDonaldCodes** [comment]
If José is not able how about asking Simon Ritter? He was last here in April and is on the Foojay OpenJDK 17+ JUG tour.

https://foojay.io/today/virtual-foojay-openjdk-17-jug-tour/

**Comment by CraigMcDonaldCodes** [comment]
Do we have a blurb for the Meetup event?

**Comment by nickebbitt** [comment]
Yeah sorry, here's what Jose messages me on Twitter 

Title: The Future of Java: Records, Sealed Classes and Pattern Matching

The release of the JDK 17 brings to interesting features in the Java language: sealed types and pattern matching for switch. Along with the introduction of records, the implementation of pattern matching in the Java language begins to take shape. This presentation shows you how records, sealed types and pattern matching can change the way we write Java code, on real patterns. It also shows you what we can expect to see on this topic in the future. It is mostly a live coding presentation, with some slides when the code shown cannot be executed. 

Passionate about programming computers for over 25 years, Jose made his debut in assembler and C, C for SIMD parallel machines before adopting Java as an object-oriented language. PhD in applied maths and computer science, assistant professor at the University Sorbonne Paris Nord for 25 years, Java Champion, JavaOne Rockstar, Jose also has a passion for education. He gives talks in major international Java conferences (JavaOne, Oracle CodeOne, Devoxx in Antwerp, Paris and London, DevNexus, GoTo).  He wrote numerous technical articles on Java technologies for Java Magazine, Oracle Technolgy Network among other publication. He is a member of the french Paris Java User Group, has been a co-organizer of the conference Devoxx France for three years, and disorganizer of JChateau, an unconference held in the Chateau of the Loire Valley. He maintains a french YouTube channel with more than 80 hours of Java courses. He is also a Pluralsight author in the Java space. He is now Java developer advocate at Oracle.

**Comment by CraigMcDonaldCodes** [comment]
Recording at https://www.youtube.com/watch?v=HGjcrheS7BU.
