### ISSUE TITLE
Money Supermarket - Tuesday 23th November 2021 18:00 - 20:00

### ISSUE THREAD

**Issue by nickebbitt** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#26]
In contact with Rob Bowley (Technology Director @ MSM).

Rob reaching out for speakers within MSM, we'll also see who else we have that would like to speak.

**Comment by nickebbitt** [comment]
Draft event: https://www.meetup.com/ManchesterUK-Java-Community/events/281867165/

**Comment by CraigMcDonaldCodes** [comment]
Event was not recorded.
