### ISSUE TITLE
Testcontainers - Kevin Wittek - Wednesday 15th December @ 12:30

### ISSUE THREAD

**Issue by nickebbitt** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#27]
https://twitter.com/Kiview

Mid-December

**Comment by nickebbitt** [comment]
Let's see if this works... :)

Hey @kiview - please can you provide an abstract and speaker bio for your talk?

**Comment by nickebbitt** [comment]
> Btw. it is Testcontainers, no camel-case 😅
Fixed :)

**Comment by CraigMcDonaldCodes** [comment]
Recording at https://www.youtube.com/watch?v=KKk0X5AkIJw.
