### ISSUE TITLE
Java Generics: Past, Present and Future - Richard Warburton 28th July @ 18:00

### ISSUE THREAD

**Issue by CraigMcDonaldCodes** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#28]
As per the title, find someone willing to give a talk on generics at an intermediate to advanced level.

- Type erasure
- Upper and lower bounds
- wildcards
- PECS

**Comment by CraigMcDonaldCodes** [comment]
I thought about approaching Richard Warburton. Not sure if we have any connections with him.

https://twitter.com/RichardWarburto
https://github.com/RichardWarburton

**Comment by nickebbitt** [comment]
As discussed in slack, I'll take an action to reach out to him

**Comment by CraigMcDonaldCodes** [comment]
Looks like Zoom borked the recording so no YouTube link.
