### ISSUE TITLE
Deep-Dive into Java's Striped64 - Heinz Kabutz - Thursday 3rd February @ 12:30 GMT

### ISSUE THREAD

**Issue by CraigMcDonaldCodes** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#29]
Intermediate to advanced level talk on concurrency.

- Memory model
- Threads and thread safety
- ExecutorService
- Concurrency problems

**Comment by CraigMcDonaldCodes** [comment]
I thought about asking Heinz Kabutz. IIRC @nickebbitt knows him.

https://twitter.com/heinzkabutz

**Comment by nickebbitt** [comment]
Yeah, happy to reach out to him, leave it with me

**Comment by kabutz** [comment]
Very happy to help! When would you like to do this?

**Comment by nickebbitt** [comment]
Hi @kabutz - how would Thursday 13th January work for you?

We often run meetup over lunchtime, so 12:30-13:30 GMT or alternatively we could schedule for an evening starting around 18:00 GMT.

**Comment by CraigMcDonaldCodes** [comment]
No recording, sorry.
