### ISSUE TITLE
The JVM Lunch (Pilot) - Thursday 13th January 2022 @ 12:30

### ISSUE THREAD

**Issue by nickebbitt** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#35]
Hosts:
- @nickebbitt 
- @jonbullock 

Intro:
- What/why this session?
  - fairly relaxed/informal discussion about current trends/news in the ecosystem
  - in future we'd look to have guests
- Host introductions
- Announcements:
  - 14th January 2022 - DevoxxUK CfP Closes
  - 20th January 2022 - https://jchampionsconf.com
  - 3rd February 2022 - Heinz Kabutz / concurrency

Proposed topics:
- Log4Shell
   - what we know about it
   - how it has impacted us in our orgs (if allowed to discuss)
   - the impact on OSS from both a maintainer and consumer perspective
   - References:
     - https://snyk.io/blog/log4shell-remediation-cheat-sheet/
     - https://snyk.io/blog/open-source-npm-packages-colors-faker/
- Java 17.0.2
  - quarterly patch release
  - usually not very interesting
  - Nick to tell story of the String dedupe leak we experienced at Auto Trader
- Java 18
  - what's in it
  - thoughts on its adoption
  - thoughts on 6 month release cycle
  - thoughts on proposal to move to 2 year LTS cycle
  - References:
    - https://openjdk.java.net/projects/jdk/18/
    - https://foojay.io/almanac/jdk-18/

**Comment by CraigMcDonaldCodes** [comment]
Are we targeting longer than the 30 minutes initially mentioned?

**Comment by nickebbitt** [comment]
I don't think it needs to be strictly 30 mins, don't want to go on too long though so we'll need to keep an eye how much time we spend on each topic

saying that, we may end up being finished after 15 mins 😄 I doubt it though

**Comment by CraigMcDonaldCodes** [comment]
Recording at https://www.youtube.com/watch?v=4GeU2MvSSSs.
