### ISSUE TITLE
Introduction to Micronaut - Sergio del Amo Caballero - 17th March 2022 @ 12:30pm GMT

### ISSUE THREAD

**Issue by CraigMcDonaldCodes** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#36]
We have not had anyone on to speak about and/or demo Micronaut. It would be nice to get someone on for the topic.

Blurb from the website:

> _A modern, JVM-based, full-stack framework for building modular, easily testable microservice and serverless applications_
> https://micronaut.io

**Comment by CraigMcDonaldCodes** [comment]
I thought maybe @timyates would know someone.

**Comment by timyates** [comment]
Does the MJC have an email address?  I can send an introduction email?

After only 2 weeks, I'm probably not the most proficient person to give a talk 😉

Give me a while though and I'll get there

**Comment by CraigMcDonaldCodes** [comment]
Sure do. Thanks Tim.

organisers@manchesterjavacommunity.org

**Comment by timyates** [comment]
Intro email sent 😁

**Comment by CraigMcDonaldCodes** [comment]
Recording at https://www.youtube.com/watch?v=5UrKY3SbOkg.
