### ISSUE TITLE
Talk from Matt Raible 25th October @ 17:00

### ISSUE THREAD

**Issue by jonbullock** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#37]
Developer Advocate at Okta.

Previous talks: https://speakerdeck.com/mraible

**Comment by CraigMcDonaldCodes** [comment]
What topic?

**Comment by jonbullock** [comment]
He's got a few talks so I thought if we can get him on, we could give the community the choice.

**Comment by Daveu1983** [comment]
Talk confirmed 25/10 list of talks available below. Poll on Slack to see what talk people want.

1. Micro Frontends for Java Microservices

You've figured out how to split up your backend services into microservices and scale your teams to the moon. But what about the frontend? Are you still building monoliths for your UI? If so, you might want to check out micro frontends—basically extensions to the microservices pattern, where the concept is extended to the frontend. Find out how to package and deploy your microservices and their UIs in the same artifact, as well as make it possible to test and develop them independently. We show how to build a microservices and micro frontends architecture using Angular, Spring Boot, and Spring Cloud.

2. Reactive Microservices with Spring Boot and JHipster

Microservice architectures are all the rage in JavaLand. They allow teams to develop services independently and deploy autonomously.

Why microservices?

IF
  you are developing a large/complex application
AND
  you need to deliver it rapidly, frequently, and reliably over a long period of time
THEN
  the Microservice Architecture is often a good choice.

Reactive architectures are becoming increasingly popular for organizations that need to do more, with less hardware. Reactive programming allows you to build systems that are resilient to high load.

In this session, I'll show you how to use JHipster to create a reactive microservices architecture with Spring Boot, Spring Cloud, Keycloak, and run it all in Docker. You will leave with the know-how to create your own resilient apps!

3. Comparing Native Java REST API Frameworks

Use Spring Boot! No, use Micronaut!! Nooooo, Quarkus is the best!!! What about Helidon?

There are a lot of developers praising the hottest, and fastest, Java REST frameworks: Micronaut, Quarkus, Spring Boot, and Helidon. In this session, you'll learn how to do the following with each framework:

✅ Build a REST API
✅ Secure your API with OAuth 2.0
✅ Optimize for production with Docker and GraalVM

I'll also share some performance numbers and pretty graphs to compare community metrics.

4. Web App Security for Java Developers

Web app security is not just authentication and authorization. It's also the things you do to protect your web app from attackers with their XSS (cross-site scripting), SQL injection, DoS/DDoS attacks, and CSRF (cross-site request forgery), to name a few.

Web app security is a central component of any web-based business. The internet exposes web apps to attacks from different locations and various levels of scale and complexity. Web application security deals specifically with the security surrounding websites, web applications, and web services such as APIs.

In this presentation, you'll learn seven ways to better web app security, using Spring Security for code samples. You'll also see some quick demos of Spring Boot, Angular, and JHipster with Okta.

**Comment by Daveu1983** [comment]
Meetup confirmed at Infinity Works, 5th Floor, 2 Circle Square, M1 7FS

What3Words link for door to 2 Circle Square ///belt.skips.stem https://w3w.co/belt.skips.stem

Venue is available from 5-8pm.

Once we have the details of the talk, they will do a post on linkedin and share our meetup link.

Offered a hybrid event, but we're going in person only.

Will arrange a call to discuss details with Ann and Kaily @infinty works.

**Comment by Daveu1983** [comment]
next steps:-
1. Take results on the poll Sunday 02/10
    a. Once known email Matt with result and where the meetup will take place.
2. Arrange a call with infinity works to discuss details
3. Create meetup entry
4. promote on socials/emails

**Comment by Daveu1983** [comment]
Talk confirmed - Comparing Native Java REST API Frameworks
Emailed Matt with confirmation
Emailed Ann with details of the talk and asked if Infinity Works can supply refreshments

**Comment by Daveu1983** [comment]
Meetup link at https://www.meetup.com/manchesteruk-java-community/events/288817776/, published the event and sent to Ann and Matt

Infinty works will cater we need to decide from https://www.gourmetgalleycatering.com/

**Comment by CraigMcDonaldCodes** [comment]
Completed, no recording as in person.
