### ISSUE TITLE
Hazelcast talk by Fawaz Ghali

### ISSUE THREAD

**Issue by CraigAMcDonald** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#52]
# Title
Simplifying Real-time Stream Processing Microservices at Scale on the Cloud

# Abstract
Real-time stream processing is growing exponentially in recent years, businesses need to gather insights from real-time data as soon as it’s generated. To do this, developers and software architects use various pipelines and tools to capture and process data in motion. Real-time stream processing has its own challenges such as testing and life-cycle management, scaling and performance, event time and late events, streaming fault tolerance, and processing guarantees. In this talk, I will address those challenges and demonstrate the best practices for real-time stream processing, from data ingestion to data processing with ultra-low latency at scale and at speed, using the Hazelcast platform. I will discuss how you can optimize your real-time streaming projects in the following areas: scalability, performance, failover, reliability, and data recovery.

# Bio
Fawaz Ghali is a Principal Developer Advocate at Hazelcast with 20+ years of experience in software development, machine learning and real-time intelligent applications. He holds a PhD in Computer Science and has worked in the private sector as well as Academia as a Researcher and Senior Lecturer. He has published over 46 scientific papers in the fields of machine learning and data science. His strengths and skills lie within the fields of low latency applications, IoT & Edge, distributed systems and cloud technologies.

**Comment by Daveu1983** [comment]
Infinty works confirmed meet up 1/3/2023. 
Await talk details, meetup event to be drafted when we have this
Call with infinity works w/c 6/2 to go through details.

**Comment by nickebbitt** [comment]
@Daveu1983 added talk details

**Comment by Daveu1983** [comment]
Event happened 1/4
