### ISSUE TITLE
Nicolai Parlog - Why Don't They Just... ?! The Deliberations Behind Evolving Java - 15th July 2021 @ 12:30pm

### ISSUE THREAD

**Issue by nickebbitt** [ManchesterJavaCommunity/manchesterjavacommunity.github.io#9]
https://nipafx.dev/talk-just/

@jonbullock to contact Nicolai

**Comment by jonbullock** [comment]
I'll e-mail Nicolai to check he's OK with the event being recorded and uploaded to our Youtube channel.

**Comment by jonbullock** [comment]
Nicolai is OK with us recording the event
